### ISSUE TITLE
Failed testing the changes provided by the use_devtools branch

### ISSUE THREAD

**Issue by mstfdkmn** [irods/irods_client_library_r_cpp#7]
Hello, we wanted to test the ´rirods´ as a R client and therefore I did try to use updates which exist in the use_devtools branch seen at #5 . But I could not succeed compiling and installing the `rirods`. The main reason for this seems dependencies issues with irods external. Please see below the steps and errors:

- In an ubuntu 18 test environment, I installed all the specified system requirements as well as r-base.
- I also installed iCommands to get authenticated easily and securely bearing in mind the following; 

> It is recommended to run the `iinit` iCommand from outside R. All `rirods` functions will honor this authentication.

- And lastly I wanted to install the package itself by executing: `devtools::install_github("MartinSchobben/irods_client_library_r_cpp", ref="use_devtools")`

The issues I encountered are:
- The L10 in the Description file has missing com,a at the end,
- Having more than one maintainer (cre) in the same file gave an error,
- Once I want to install the package I got a compilation error:
`g++: error: unrecognized command line option ‘-stdlib=libc++’`
- I removed the `-stdlib=libc++` at L10 in the Makevars file (also converted -O0 to -O2 to test) and tried it again and got many like below:
```
/opt/irods-externals/json3.7.3-0/include/json.hpp:14431:22: error: ‘isfinite’ is not a member of ‘std’
            if (not std::isfinite(x))
```
- Apparently it needs some headers like `#include<cmath>` and `#include <cstdlib>` in json, or?
- I tested using the provided Dockerfile but I got the same results. 
- Also, when I wanted to build the image and run a container with `build-rirods.sh`, it complained about PATH at the L18.

Some basic, newbie questions to understand better:
- The name of the first commit in the PR is about 'compiles against 4.3.0!' but the iRODS system requirements for this package use the latest available repository/binary. Can I say this could be a reason for my installing issue?
- As a system requirement, an old complier version is needed - `clang6.0.0`
- It needs a c library as a system requirements `jansson2.7-0` for cpp used in the package.

Lastly,
What mistake might I have made? could you elaborate how I can test this library to use against 4.2.10? Or it is too early now to test and use it as a R client? Thanks.

**Comment by trel** [comment]
Note: This repository has been deprecated and archived.

Please find a new pure-R implementation at:

https://github.com/irods/irods_client_library_rirods
